name: Compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  compile:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Bork
      uses: actions/checkout@v2
      with:
        repository: 'skylarmacdonald/bork'
        path: 'bork_source'
    - name: Link Bork
      run: echo "$GITHUB_WORKSPACE/bork_source/bin" >> $GITHUB_PATH
    - name: Compile Bork
      run: ./compile_bork.sh
    - name: Upload Bork script
      uses: actions/upload-artifact@v2
      with:
        path: bork.sh
